### ISSUE TITLE
Mark `<mark>` somewhere

### ISSUE THREAD

**Issue by RichardLitt** [bevacqua/es6#2]
I hadn't seen the notation that you're using here, `<mark>`, as a way to point out something to mark in the code before. It would be useful to explain that ES6 isn't reverting to XML, and that this is simply how you're directing the reader's eyes.

**Comment by bevacqua** [comment]
These are used in the original article on my blog to add HTML `<mark>` tags and highlight bits of code and text.

Example:
<img width="537" alt="screen shot 2015-11-19 at 12 21 17" src="https://cloud.githubusercontent.com/assets/934293/11274533/10ac81fc-8eb8-11e5-9544-a33084179b57.png">
