### ISSUE TITLE
Translate documentation for portuguese (PT-BR) 

### ISSUE THREAD

**Issue by iamfelipemattos** [bevacqua/es6#8]
i'm translating into portuguese the brazil

**Comment by bevacqua** [comment]
Awesome!! You can PR it as `readme-pt-br.markdown`

**Comment by bsides** [comment]
Nice. If you need any help in translating @IAMFELIPEMATTOS let me know!

**Comment by iamfelipemattos** [comment]
in progress @bevacqua > https://github.com/IAMFELIPEMATTOS/es6/blob/master/readme-pt-br.markdown

**Comment by iamfelipemattos** [comment]
cc: @bsides
